version: "3.8"

volumes:
  database_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  app:
    image: "php:8.2-apache"
    build:
      context: .docker/php
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html


  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - "33061:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - php_advanced

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - php_advanced

